### ISSUE TITLE
Interconversion between `template string` and `string`

### ISSUE THREAD

**Issue by alexzhang1030** [antfu/eslint-plugin-command#1]
### Clear and concise description of the problem

I would like to use a command to interconvert between `template string` and `string`.

### Suggested solution

Interconversion would be easy, if there are multiple strings in one line, we can specify the number or all to covert.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Would you like to work on that? Thanks

**Comment by alexzhang1030** [comment]
> Would you like to work on that? Thanks

I would love to do❤️
