### ISSUE TITLE
`/// keep-sorted` for `import/export` statements

### ISSUE THREAD

**Issue by pauliesnug** [antfu/eslint-plugin-command#19]
### Clear and concise description of the problem

Hiya! Basically, just a way to keep import/export statements sorted (including the elements imported within them). Some of this might fit into an entirely separate ESLint rule, but I feel like especially the first example below would fit into this plugin.

#### basic `export`
```ts
/// keep-sorted
export * from './bbbbbbbbbb.ts';
export * from './aaaaaaaaaaa.ts';

// ->

/// keep-sorted
export * from './aaaaaaaaaaa.ts';
export * from './bbbbbbbbbb.ts';
```

#### basic `import`
```ts
/// keep-sorted
import { d, c, b, a } from './bbbbbbbbbb.ts';
import * as bbb from './bbbbbbbbbbc.ts';
import { dd, cc, aa, bb } from './aaaaaaaaaaa.ts';
import * as aaa from './aaaaaaaaaaac.ts';

// everything below isnt sorted i guess? not sure of details
import ....

// ->

/// keep-sorted
import * as aaa from './aaaaaaaaaaac.ts'; // wildcard `as` imports would have more priority based on their aliased name
import * as bbb from './bbbbbbbbbbc.ts';
import { aa, bb, cc, dd } from './aaaaaaaaaaa.ts';
import { a, b, c, d } from './bbbbbbbbbb.ts';

// everything below isnt sorted i guess? not sure of details
import ....
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Ideally this should already be handled by https://eslint.org/docs/latest/rules/sort-imports

I see now reason why you don't always sort them but want to do it on-demand
